# Generated by Django 5.0.7 on 2024-07-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
